<Project>
  <Target Name="_GetPdbPackageFiles">
    <ItemGroup>
      <_PdbFile Include="$([System.IO.Path]::ChangeExtension($(TargetPath), '.pdb'))"
                Condition="'$(Configuration)' == 'Debug' or '$(IncludeDebugSymbols)' == 'true'" />
      <AllSourceFiles Include="@(_PdbFile)">
        <TargetDir></TargetDir>
        <TargetName>%(Filename)</TargetName>
        <TargetExt>%(Extension)</TargetExt>
        <IncludeInWheel>true</IncludeInWheel>
        <IncludeInSdist>false</IncludeInSdist>
      </AllSourceFiles>
    </ItemGroup>
  </Target>

  <PropertyGroup>
    <GetPackageFilesTargets>_GetPdbPackageFiles;$(GetPackageFilesTargets)</GetPackageFilesTargets>
  </PropertyGroup>

  <ItemDefinitionGroup Condition="'$(IncludeDebugSymbols)' == 'true'">
    <ClCompile>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
    </ClCompile>
    <Link>
      <GenerateDebugInformation>true</GenerateDebugInformation>
    </Link>
  </ItemDefinitionGroup>

  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" Condition="$(VCTargetsPath) != ''" />
</Project>
