name: PyPI Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install packaging twine
    - name: Build
      run: python -m pymsbuild -d dist sdist wheel
      env:
        GITHUB_REF: ${{ github.ref }}
    - name: Push
      run: python -m twine upload dist\*
      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.pypi }}
