name: PyPI Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install packaging
    - name: Build sdist
      run: python -m pymsbuild -d dist sdist
      env:
        GITHUB_REF: ${{ github.ref }}
    - name: Build wheel
      run: python -m pymsbuild -d dist wheel
      env:
        GITHUB_REF: ${{ github.ref }}
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
